### ISSUE TITLE
add new fields in volunteers form

### ISSUE THREAD

**Issue by rashivkp** [rashivkp/rescuekerala#1]
area_willing_to_support
is_smartphone 
availability 
sevice_type 
sevice_group
sevice_item

**Comment by nishad** [comment]
Clarifying :
is_smartphone - Check box ?
availability - Input Type ?
sevice_type - Input Type ?
sevice_group - Input Type ?
sevice_item - Input Type ?

**Comment by rashivkp** [comment]
is_smartphone - Check box 
availability - text box,  helptag like Day/Night/Hours
sevice_type - multiple select
sevice_group - multiple select
sevice_item - multiple select

**Comment by rashivkp** [comment]
Rescue	
----In Site Rescue----
--------Boat 
--------Heavy Vehicles
--------LMV
--------Volunteer
----Relief Camps
--------Medical
--------Food
--------Transportation
--------Volunteer

Food----
----Store----
--------Packed Food
--------Raw Materials
--------Drinking Water

----Transportation----
--------Heavy Vehicle
--------LMV
----Distribution----
--------Volunteer
Medical Assistance----
----Doctor----
--------Can work at Relief Camp
--------Other
----Nursing Staff----
--------Can work at Relief Camp
--------Other
----Pharmacist
--------Willing to work at Relief Camp
--------Other
----Medicine----
--------Store
--------Transportation
--------Nursing
----Ambulance----
--------With Life supporting Instruments
--------W/O LSI

**Comment by rashivkp** [comment]
@nishad when implementing multiple-select, filtering is not needed right ? what you think ?

**Comment by nishad** [comment]
Yes, They only need to select applicable service items. 
And we can verify at-least one service item is selected. How about that ?
